name: Build & attach release binaries
on:
  release:
    types: [published, edited]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Attach release binaries to made release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Download NodeJS deps
        working-directory: scripts/js
        run: yarn install
      - name: Build dsgore
        run: bash scripts/bash/build.sh
      - name: Attach built binary to release
        working-directory: scripts/js
        run: node attach-release.js
        env:
          GHTOKEN: ${{ secrets.GITHUB_TOKEN }}
